
INSERT INTO [dbo].[Categories] ([Name]) VALUES(N'Dairy')
INSERT INTO [dbo].[Categories] ([Name]) VALUES(N'Vegetables')
INSERT INTO [dbo].[Categories] ([Name]) VALUES(N'Fruits')
INSERT INTO [dbo].[Categories] ([Name]) VALUES(N'Grains')
INSERT INTO [dbo].[Categories] ([Name]) VALUES(N'Meat')
INSERT INTO [dbo].[Categories] ([Name]) VALUES(N'Breakfast')
INSERT INTO [dbo].[Categories] ([Name]) VALUES(N'Dinner')

INSERT INTO [dbo].[Products] ([Name]) VALUES(N'Milk')
INSERT INTO [dbo].[Products] ([Name]) VALUES(N'Potato')
INSERT INTO [dbo].[Products] ([Name]) VALUES(N'Carrot')
INSERT INTO [dbo].[Products] ([Name]) VALUES(N'Orange')
INSERT INTO [dbo].[Products] ([Name]) VALUES(N'Nuts')
INSERT INTO [dbo].[Products] ([Name]) VALUES(N'Beans')
INSERT INTO [dbo].[Products] ([Name]) VALUES(N'Bread')
INSERT INTO [dbo].[Products] ([Name]) VALUES(N'Pasta')

INSERT INTO [dbo].[ProductsCategories] ([ProductId], [CategoryId]) VALUES(1, 1)
INSERT INTO [dbo].[ProductsCategories] ([ProductId], [CategoryId]) VALUES(1, 6)
INSERT INTO [dbo].[ProductsCategories] ([ProductId], [CategoryId]) VALUES(2, 2)
INSERT INTO [dbo].[ProductsCategories] ([ProductId], [CategoryId]) VALUES(2, 7)
INSERT INTO [dbo].[ProductsCategories] ([ProductId], [CategoryId]) VALUES(3, 2)
INSERT INTO [dbo].[ProductsCategories] ([ProductId], [CategoryId]) VALUES(3, 7)
INSERT INTO [dbo].[ProductsCategories] ([ProductId], [CategoryId]) VALUES(4, 3)
INSERT INTO [dbo].[ProductsCategories] ([ProductId], [CategoryId]) VALUES(4, 6)
INSERT INTO [dbo].[ProductsCategories] ([ProductId], [CategoryId]) VALUES(5, 4)
INSERT INTO [dbo].[ProductsCategories] ([ProductId], [CategoryId]) VALUES(7, 4)
INSERT INTO [dbo].[ProductsCategories] ([ProductId], [CategoryId]) VALUES(7, 6)
INSERT INTO [dbo].[ProductsCategories] ([ProductId], [CategoryId]) VALUES(7, 7)
INSERT INTO [dbo].[ProductsCategories] ([ProductId], [CategoryId]) VALUES(8, 7)
GO
